[package]
name = "minidump-gen-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "minidump-gen-cli"
path = "src/main.rs"

[dependencies]
minidump-handler = { path = "../minidump-handler" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
colored = "2"

